# Install CVMFS Stratum 1 server(s).
---
- name: CVMFS Stratum 1
  hosts: cvmfsstratum1servers
  pre_tasks:
    - name: Fix that adds additional dependencies for Debian systems
      set_fact:
        cvmfs_packages:
          stratum1:
            - apache2
            - "{{ 'libapache2-mod-wsgi-py3' if ansible_distribution_release in ('bookworm', 'jammy') else 'libapache2-mod-wsgi' }}"
            - squid
            - cvmfs-server
            - cvmfs-config-default
      when: ansible_facts['os_family'] == 'Debian'
  roles:
    - role: geerlingguy.repo-epel
      when: ansible_facts['os_family'] == 'RedHat'
    - galaxyproject.cvmfs
